<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('transliterate')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_transliterate.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('transliterate.so')) return;
    } else {
      if (!dl('transliterate.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class transliterate {
	static function greek_beta_to_utf8($beta) {
		return greek_beta_to_utf8($beta);
	}

	static function greek_utf8_to_beta($utf8) {
		return greek_utf8_to_beta($utf8);
	}
}

/* PHP Proxy Classes */

?>
